DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS locations CASCADE;

DROP TABLE IF EXISTS events CASCADE;

DROP TABLE IF EXISTS requests CASCADE;

DROP INDEX IF EXISTS requests_id_status_idx;

DROP TABLE IF EXISTS compilations CASCADE;

DROP TABLE IF EXISTS events_compilations CASCADE;

DROP TABLE IF EXISTS users_subscriptions CASCADE;

CREATE TABLE IF NOT EXISTS users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(256) NOT NULL,
    email VARCHAR(256) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS categories
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(256) NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT categories_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    lat numeric NOT NULL,
    lon numeric NOT NULL,
    CONSTRAINT locations_pkey PRIMARY KEY (id),
    CONSTRAINT locations_lat_lon_key UNIQUE (lat, lon)
);

CREATE TABLE IF NOT EXISTS events
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    annotation text  NOT NULL,
    category_id bigint,
    description text  NOT NULL,
    event_date timestamp without time zone  NOT NULL,
    initiator_id bigint,
    location_id bigint,
    is_paid boolean DEFAULT FALSE,
    participiant_limit integer DEFAULT 0,
    published_date timestamp without time zone,
    is_moderated boolean  NOT NULL,
    state VARCHAR(64),
    title text NOT NULL,
    create_date timestamp without time zone NOT NULL,
    CONSTRAINT events_pkey PRIMARY KEY (id),
    CONSTRAINT events_category_id_fkey FOREIGN KEY (category_id)
        REFERENCES categories (id),
    CONSTRAINT events_initiator_id_fkey FOREIGN KEY (initiator_id)
        REFERENCES users (id),
    CONSTRAINT events_location_id_fkey FOREIGN KEY (location_id)
        REFERENCES locations (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    requester_id bigint,
    event_id bigint,
    created timestamp without time zone NOT NULL,
    status VARCHAR(64),
    CONSTRAINT  requests_pkey PRIMARY KEY (id),
    CONSTRAINT requests_requester_id_fkey FOREIGN KEY (requester_id)
        REFERENCES users (id),
    CONSTRAINT requests_event_id_fkey FOREIGN KEY (event_id)
        REFERENCES events (id)
);


CREATE TABLE IF NOT EXISTS compilations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    is_pinned boolean DEFAULT FALSE,
    title text NOT NULL,
    CONSTRAINT compilations_pkey PRIMARY KEY (id),
    CONSTRAINT compilations_title_key UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    compilation_id bigint,
    event_id bigint,
    CONSTRAINT events_compilations_pkey PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT events_compilations_compilation_id_fkey FOREIGN KEY (compilation_id)
        REFERENCES compilations (id),
    CONSTRAINT events_compilations_event_id_fkey FOREIGN KEY (event_id)
        REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS users_subscriptions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint,
    subscriber_id bigint,
    status VARCHAR(64),
    CONSTRAINT users_subscriptions_pkey PRIMARY KEY (id),
    CONSTRAINT users_subscriptions_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES users (id),
    CONSTRAINT users_subscriptions_subscriber_id_fkey FOREIGN KEY (subscriber_id)
        REFERENCES users (id),
    CONSTRAINT users_subscriptions_subscriber_unique UNIQUE (user_id, subscriber_id)
);




