DROP TABLE IF EXISTS hits CASCADE;

CREATE TABLE IF NOT EXISTS hits
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app text NOT NULL,
    uri text NOT NULL,
    ip text NOT NULL,
    dttm timestamp without time zone,
    CONSTRAINT hits_pkey PRIMARY KEY (id)
    );

